# Generated by Django 5.1.4 on 2025-02-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accommodations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookingarticle",
            name="area",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
