# Generated by Django 5.1.4 on 2025-01-29 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accommodations", "0002_housearticle_user_phone_user_user_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addtionallinfomaion",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accommodations.acquistionarticle",
            ),
        ),
    ]
